Controllers/CompanyController.cs
using goLaundryWebApp.Common;
using goLaundryWebApp.Models;
using goLaundryWebApp.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace goLaundryWebApp.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ILogger<CompanyController> _CompLogger;
        private readonly ILogger<GridViewController> _GridLogger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISession _session;
        Session clsSession = null;
        private readonly string compInfoViewHtml = @"~/Views/Company/CompanyInfo.cshtml";

        public CompanyController(IHttpContextAccessor httpContextAccessor, ILogger<CompanyController> logger, ILogger<GridViewController> gridlogger)
        {
            _CompLogger = logger;
            _GridLogger = gridlogger;
            _httpContextAccessor = httpContextAccessor;
            _session = _httpContextAccessor.HttpContext.Session;
            clsSession = new Session(_httpContextAccessor);
        }


        public IActionResult AddCompany()
        {
            CompanyModel objComp = new CompanyModel();

            TempData["pageMode"] = ConstantVar.PageModeAdd;

            return View(compInfoViewHtml, objComp);
        }

        public IActionResult EditCompany(int CompId)
        {

            CompanyModel objComp = new CompanyModel();

            TempData["pageMode"] = ConstantVar.PageModeEdit;
            ViewData["Title"] = "Edit Company";

            string apiCall = APIUrlCallVar.api_ViewEditCompany;
            apiCall = apiCall.Replace("$", CompId.ToString());

            Task<ResponseModel> respReturn = new CommonAPI().APICallGetMethod(apiCall);
            respReturn.Wait();
            ResponseModel resp = respReturn.Result;
            DataSet dsData = CommonAPI.dataJsonToDataSet(resp.data);

            DataTable dtCompDetails = dsData.Tables[0];
            if (dtCompDetails.Rows.Count > 0)
            {
                objComp.compId = Convert.ToInt32(dtCompDetails.Rows[0]["iCOID"]);
                objComp.compName = dtCompDetails.Rows[0]["vaCONAME"].ToString();
                objComp.branchName = dtCompDetails.Rows[0]["vaBRANCH"].ToString();
                objComp.email = dtCompDetails.Rows[0]["vaEMAIL"].ToString();
                objComp.telNo = dtCompDetails.Rows[0]["vaTELNO"].ToString();
                objComp.faxNo = dtCompDetails.Rows[0]["vaFAXNO"].ToString();
                objComp.add1 = dtCompDetails.Rows[0]["vaADD1"].ToString();
                objComp.add2 = dtCompDetails.Rows[0]["vaADD2"].ToString();
                objComp.add3 = dtCompDetails.Rows[0]["vaADD3"].ToString();
                objComp.isActive = Convert.ToBoolean(dtCompDetails.Rows[0]["siSTATUS"].ToString());
            }


            return View(compInfoViewHtml, objComp);
        }

        public IActionResult ViewCompany(int CompId)
       {
            CompanyModel objComp = new CompanyModel();
            TempData["pageMode"] = ConstantVar.PageModeView;
            ViewData["Title"] = "View Company";

            string apiCall = APIUrlCallVar.api_ViewEditCompany;
            apiCall = apiCall.Replace("$", CompId.ToString());

            Task<ResponseModel> respReturn = new CommonAPI().APICallGetMethod(apiCall);
            respReturn.Wait();
            ResponseModel resp = respReturn.Result;
            DataSet dsData = CommonAPI.dataJsonToDataSet(resp.data);

            DataTable dtCompDetails = dsData.Tables[0];
            if (dtCompDetails.Rows.Count > 0)
            {
                objComp.compId = Convert.ToInt32(dtCompDetails.Rows[0]["iCOID"]);
                objComp.compName = dtCompDetails.Rows[0]["vaCONAME"].ToString();
                objComp.branchName = dtCompDetails.Rows[0]["vaBRANCH"].ToString();
                objComp.email = dtCompDetails.Rows[0]["vaEMAIL"].ToString();
                objComp.telNo = dtCompDetails.Rows[0]["vaTELNO"].ToString();
                objComp.faxNo = dtCompDetails.Rows[0]["vaFAXNO"].ToString();
                objComp.add1 = dtCompDetails.Rows[0]["vaADD1"].ToString();
                objComp.add2 = dtCompDetails.Rows[0]["vaADD2"].ToString();
                objComp.add3 = dtCompDetails.Rows[0]["vaADD3"].ToString();
                objComp.strIsActive = CommonFunction.convertStatusToStr(Convert.ToBoolean(dtCompDetails.Rows[0]["siSTATUS"].ToString()));
            }


            #region gridSetup
            GridViewController objGridViewCtrl = new GridViewController(_httpContextAccessor, _GridLogger);
            ListGridView objListGridView = new ListGridView();
            objListGridView.GridView = new List<GridView>();
            objListGridView.GridView.Add(new GridView("dtGridChildCompList"));

            objListGridView.GridView[0].ColumnHide = new int[] { 0 };
            objListGridView.GridView[0].ColumnNoSort = new int[] { };
            objListGridView.GridView[0].IsCheckBoxRequired = "N";
            objListGridView.GridView[0].ColumnWidth = new string[] { "", "55%", "35%" };
            objListGridView.GridView[0].GridViewModuleName = "Administration";
            objListGridView.GridView[0].GridViewSubModuleName = "CompanyChildList";
            objListGridView.GridView[0].dtGridView = dsData.Tables[1];
            objListGridView.GridView[0].actionSetup = "btnView,View,fas fa-eye,#";

            objListGridView.GridView.Add(new GridView("dtUserCompList"));
      
            objListGridView.GridView[1].ColumnHide = new int[] { 0 , 1};
            objListGridView.GridView[1].ColumnNoSort = new int[] { };
            objListGridView.GridView[1].IsCheckBoxRequired = "N";
            objListGridView.GridView[1].ColumnWidth = new string[] { "", "", "55%", "35%" };
            objListGridView.GridView[1].GridViewModuleName = "Administration";
            objListGridView.GridView[1].GridViewSubModuleName = "CompanyUserList";
            objListGridView.GridView[1].actionSetup = "btnView,View,fas fa-eye,#";
            objListGridView.GridView[1].dtGridView = dsData.Tables[2];

            clsSession.setSession("sessionGridView", JsonConvert.SerializeObject(objListGridView));

            objGridViewCtrl.GridViewListingReturn();

            #endregion

            return View(compInfoViewHtml, objComp);
        }

        public IActionResult CompanyList()
        {
            //string menuSessStr = clsSession.getSession("sessionUserMenuPerm");
            //DataTable objSessionUserMenuPerm = JsonConvert.DeserializeObject<DataTable>(menuSessStr);

            GridViewController objGridViewCtrl = new GridViewController(_httpContextAccessor, _GridLogger);
            ListGridView objListGridView = new ListGridView();
            objListGridView.GridView = new List<GridView>();
            objListGridView.GridView.Add(new GridView("dtGridCompList"));

            objListGridView.GridView[0].ColumnHide = new int[] { 0 };
            objListGridView.GridView[0].ColumnNoSort = new int[] {  };
            objListGridView.GridView[0].IsCheckBoxRequired = "N";
            objListGridView.GridView[0].ColumnWidth = new string[] { "", "40%", "12.5%", "12.5%", "12.5%", "12.5%", "" };
            objListGridView.GridView[0].GridViewModuleName = "Administration";
            objListGridView.GridView[0].GridViewSubModuleName = "CompanyList";
            objListGridView.GridView[0].GridViewApiCall = APIUrlCallVar.api_CompanyGridList;
            objListGridView.GridView[0].actionSetup = "btnEdit,Edit,fas fa-edit,#|btnView,View,fas fa-eye,#";
            //objListGridView.GridView[0].editValue1 = "iCOID";
            clsSession.setSession("sessionGridView", JsonConvert.SerializeObject(objListGridView));

            objGridViewCtrl.GridViewListingReturn();

            return View();
        }
    }
}

ViewComponents/GridPartialViewComponent.cs
using goLaundryWebApp.Common;
using goLaundryWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace goLaundryWebApp.ViewComponents
{
    public class GridPartialViewComponent : ViewComponent
    {
        private readonly ILogger<GridPartialViewComponent> _GridLogger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ISession _session;
        Session clsSession = null;
        string gridSessStr = "";

        public GridPartialViewComponent(IHttpContextAccessor httpContextAccessor, ILogger<GridPartialViewComponent> logger)
        {
            _GridLogger = logger;
            _httpContextAccessor = httpContextAccessor;
            _session = _httpContextAccessor.HttpContext.Session;
            clsSession = new Session(_httpContextAccessor);
        }

        public async Task<IViewComponentResult> InvokeAsync(int GridViewNo)
        {
            ListGridView objListGridView = new ListGridView();
            gridSessStr = clsSession.getSession("sessionGridView");
            objListGridView = JsonConvert.DeserializeObject<ListGridView>(gridSessStr);
            objListGridView.GridviewNo = GridViewNo;
            //objListGridView = HttpContext.Session.GetObjectFromJson<ListGridView>("sessionGridView");

            return View(objListGridView);
        }
    }
}

Views/Company/CompanyInfo.cshtml
@using goLaundryWebApp.Models
@model goLaundryWebApp.Models.CompanyModel
@{
    int pageMode = (int)TempData["pageMode"];
    int modeView = ConstantVar.PageModeView;
    string[] optionListIsActive = new string[] { "InActive", "Active" };
}

<div class="contentAndNav">
    <div class="panel">
        <h2 class="color-primary-04 bg-primary-03">@ViewData["Title"]</h2>
        <div class="mod--theme-secondary">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-xs-12 col-sm-12 textfield">
                            <div>
                                Company Name<span class="asterisk">*</span>
                            </div>
                        </div>

                        <div class="col-lg-10 col-md-10 col-xs-12 col-sm-12 textfield">
                            <input type="hidden" id="compId" name="compId" value="@Model.compId" />
                            <input type="text" id="compName" name="compName" Class="form-control" value="@Model.compName" />
                        </div>

                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-xs-12 col-sm-12 textfield">
                            <div>
                                Branch<span class="asterisk">*</span>
                            </div>
                        </div>
                        <div class="col-lg-10 col-md-10 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="branchName" name="branchName" Class="form-control" value="@Model.branchName" />
                        </div>
                    </div>

                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Email<span class="asterisk">*</span>
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="email" name="email" Class="form-control" value="@Model.email" />
                        </div>
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Telephone No<span class="asterisk">*</span>
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="telNo" name="telNo" Class="form-control" value="@Model.telNo" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Fax No<span class="asterisk">*</span>
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="faxNo" name="faxNo" Class="form-control" value="@Model.faxNo" />
                        </div>
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Address 1<span class="asterisk">*</span>
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="add1" name="add1" Class="form-control" value="@Model.add1" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Address 2
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="add2" name="add2" Class="form-control" value="@Model.add2" />
                        </div>
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Address 3
                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                            <input type="text" id="add3" name="add3" Class="form-control" value="@Model.add3" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">
                            Status<span class="asterisk">*</span>
                        </div>
                        @*<div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
            @if (pageMode == modeView)
            {
                <input type="text" id="strIsActive" name="strIsActive" Class="form-control" value="@Model.strIsActive" />
            }
            else
            {
        <select id="isActive" name="isActive" class="form-control js-select mandatory" value="@Convert.ToInt32(Model.isActive)">
            @for (int j = 0; j < optionListIsActive.Length; j++)
            {
                <option selected="@(Convert.ToInt32(Model.isActive)== j ? "selected" : null)" value="@j">@optionListIsActive[j].ToString()</option>
            }
        </select>
            }
        </div>*@
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">
                             <select id="isActive" name="isActive" class="form-control js-select mandatory" value="@Convert.ToInt32(Model.isActive)">
                                @for (int j = 0; j < optionListIsActive.Length; j++)
                                {
                                    <option selected="@(Convert.ToInt32(Model.isActive)== j ? "selected" : null)" value="@j">@optionListIsActive[j].ToString()</option>
                                }
                            </select>
                            
                        </div>
                        <div class="col-lg-1 col-md-1 col-xs-12 col-sm-12 textfield">

                        </div>
                        <div class="col-lg-5 col-md-5 col-xs-12 col-sm-12 textfield">

                        </div>
                    </div>
                </div>
            </div>

            <br />
            <br />
            <div class="row">
                <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12 textfield">
                    <div class="row">
                        <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12 btnfield">
                            <input type="button" id="btnBack" name="btnBack" value="<< Go To List" Class="btn btn--secondary text-center" onclick="" />
                        </div>
                        <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12 btnfield">
                            <input type="button" id="btnCreate" name="btnCreate" value="Create >>" Class="btn btn--primary text-center" onclick="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (pageMode == modeView)
{
    <div class="contentAndNav">
        <div class="panel">
            <h2 class="color-primary-04 bg-primary-03">Company Details</h2>
            <div class="mod--theme-secondary">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                        <div class="reminder">
                            Sub Company List
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                        @await Component.InvokeAsync("GridPartial", new { GridViewNo = 0 })
                    </div>
                </div>
                <br />
                <br />

                <div class="row">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 textfield">
                        <div class="reminder">
                            User List
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                        @await Component.InvokeAsync("GridPartial", new { GridViewNo = 1 })
                    </div>
                </div>

            </div>
        </div>
    </div>

}

@section scripts {
    <script>
        var pageMode = '@pageMode';
        var modeView = '@ConstantVar.PageModeView';

        $(window).on( "load", function () {
            if (pageMode == modeView) {
                $('.asterisk').hide();
                $('.textfield > .form-control').prop('disabled', true);
                $('.btnfield > .btn').hide();
            }
        });
    </script>
}

Views/Company/CompanyList.cshtml
@{
    ViewData["Title"] = "List Company";
}


<div class="contentAndNav">
    <div class="panel">
        <h2 class="color-primary-04 bg-primary-03">@ViewData["Title"]</h2>
        <div class="mod--theme-secondary">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">

                    @await Component.InvokeAsync("GridPartial")

                </div>
            </div>
        </div>
    </div>
</div>